plugins {
    id 'com.android.library'
}
 
apply plugin: 'com.diffplug.spotless'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion
	namespace = "com.tyron.builder.log"
	
    defaultConfig {
        minSdk rootProject.ext.minSdkVersion
        targetSdk rootProject.ext.targetSdkVersion
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17 
        targetCompatibility JavaVersion.VERSION_17
    }
     
}

dependencies {

    implementation('androidx.lifecycle:lifecycle-viewmodel:2.10.0-rc01')
    implementation('androidx.lifecycle:lifecycle-viewmodel-ktx:2.10.0-rc01')
    implementation('androidx.lifecycle:lifecycle-livedata:2.10.0-rc01')
    compileOnly project(path: ':android-stubs')
    implementation(projects.resources)

    // diagnostics
    implementation project(path: ':javac')
    api(libs.tooling.slf4j)
	 
}

spotless {
		java {
			target "**/*.java"
			googleJavaFormat()
			}
}